DROP TABLE IF EXISTS TBL_EMPLOYEES;
 
CREATE TABLE TBL_EMPLOYEES (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    TEAM_NAME VARCHAR(250) NOT NULL,
    COUNTRY VARCHAR(250) NOT NULL,
    FLAG_URL VARCHAR(250) NOT NULL,
    CAPTAIN VARCHAR(250) NOT NULL,
    VICE_CAPTAIN VARCHAR(250) NOT NULL,
    WICKET_KEEPER VARCHAR(250) NOT NULL,
    COUNTRY_CODE VARCHAR(250) NOT NULL,
    IS_ACTIVE BIT DEFAULT 0 NOT NULL
);